/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    KButton: typeof import('@0x-jerry/vue-kit')['KButton']
    KInput: typeof import('@0x-jerry/vue-kit')['KInput']
    NButton: typeof import('./components/NButton.vue')['default']
  }
}
